"use strict";
exports.__esModule = true;
var memoryUsage = process.memoryUsage();
global.gc();
console.log('已使用内存', memoryUsage.heapUsed);
var arr = new Array(100000);
arr.forEach(function (item) { return item = 1; });
memoryUsage = process.memoryUsage();
console.log('已使用内存', memoryUsage.heapUsed);
memoryUsage = process.memoryUsage();
console.log('已使用内存', memoryUsage.heapUsed);
arr = null;
global.gc();
memoryUsage = process.memoryUsage();
console.log('已使用内存', memoryUsage.heapUsed);
